name: RavenTube - Full (Search + Download)

on:
  workflow_dispatch:
    inputs:
      search_query:
        description: 'Search query'
        required: true

jobs:
  call_search:
    uses: ./.github/workflows/raventube-search.yml
    with:
      search_query: ${{ github.event.inputs.search_query }}
  call_download:
    needs: call_search
    uses: ./.github/workflows/raventube-download.yml
    with:
      use_latest_search: true
      quality: best
